version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: StravaWeather.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - strava-weather-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strava_weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strava-weather-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - strava-weather-network

volumes:
  postgres_data:

networks:
  strava-weather-network:
    driver: bridge